spring:
  h2:
    console:
      path: /h2
      enabled: true

#  datasource:
#    username: sa
#    password:
#    url: jdbc:h2:mem:testdb
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: spring123

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  redis:
    port: 6379
    
springdoc:
  packages-to-exclude: me.devksh930/orderapi/account/domain
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  swagger-ui:
    operations-sorter:
    enabled: true
  paths-to-match:
    - /api/auth/**
    - /api/admin/**
    - /api/orders/**
    - /api/accounts/**
    - /api/products/**

app:
  jwt:
    secretKey: c81cc9e3bd85b4efa605703f92eb7148fe5394fa68c0fea13834ab5f2ab2adeac6af25b9f07306dec810969176d6d03a538f00c6556fadb6ab212be25c68ca55
    tokenValidityTime: 21600000 #6시간

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.sql: debug

