spring:
  h2:
    console:
      path: /h2
      enabled: true

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true